config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  namespace :admin do
      resources :aiyl_aimaks
      resources :settlements
      resources :oblasts
      resources :layers
      resources :infra_projects
      resources :districts
      resources :partners
      resources :owners
      root to: "aiyl_aimaks#index"
    end
  resources :settlements, only: [:index, :show]
  resources :aiyl_aimaks, only: [:index, :show]
  resources :districts, only: [:index, :show]
  resources :oblasts, only: [:index, :show]
  resources :infra_projects, only: [:index, :show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  belongs_to :oblast
  belongs_to :district
  belongs_to :aiyl_aimak

  has_many :infra_projects, dependent: :destroy
end

app/controllers/admin/settlements_controller.rb
module Admin
  class SettlementsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
  before_action :set_settlement, only: [:show, :edit, :update, :destroy]

  # GET /settlements
  # GET /settlements.json
  def index
    @settlements = Settlement.all
  end

  # GET /settlements/1
  # GET /settlements/1.json
  def show
  end

  # GET /settlements/new
  def new
    @settlement = Settlement.new
  end

  # GET /settlements/1/edit
  def edit
  end

  # POST /settlements
  # POST /settlements.json
  def create
    @settlement = Settlement.new(settlement_params)

    respond_to do |format|
      if @settlement.save
        format.html { redirect_to @settlement, notice: 'Settlement was successfully created.' }
        format.json { render :show, status: :created, location: @settlement }
      else
        format.html { render :new }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settlements/1
  # PATCH/PUT /settlements/1.json
  def update
    respond_to do |format|
      if @settlement.update(settlement_params)
        format.html { redirect_to @settlement, notice: 'Settlement was successfully updated.' }
        format.json { render :show, status: :ok, location: @settlement }
      else
        format.html { render :edit }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settlements/1
  # DELETE /settlements/1.json
  def destroy
    @settlement.destroy
    respond_to do |format|
      format.html { redirect_to settlements_url, notice: 'Settlement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_settlement
      @settlement = Settlement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def settlement_params
      params.require(:settlement).permit(:oblast_id, :district_id, :aiyl_aimak_id, :name, :soate)
    end
end

app/helpers/settlements_helper.rb
module SettlementsHelper
end

app/views/settlements/_form.html.erb
<%= form_with(model: settlement, local: true) do |form| %>
  <% if settlement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(settlement.errors.count, "error") %> prohibited this settlement from being saved:</h2>

      <ul>
        <% settlement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :oblast_id %>
    <%= form.text_field :oblast_id %>
  </div>

  <div class="field">
    <%= form.label :district_id %>
    <%= form.text_field :district_id %>
  </div>

  <div class="field">
    <%= form.label :aiyl_aimak_id %>
    <%= form.text_field :aiyl_aimak_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :soate %>
    <%= form.text_field :soate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/settlements/edit.html.erb
<h1>Editing Settlement</h1>

<%= render 'form', settlement: @settlement %>

<%= link_to 'Show', @settlement %> |
<%= link_to 'Back', settlements_path %>

app/views/settlements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settlements</h1>

<table>
  <thead>
    <tr>
      <th>Oblast</th>
      <th>District</th>
      <th>Aiyl aimak</th>
      <th>Name</th>
      <th>Soate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settlements.each do |settlement| %>
      <tr>
        <td><%= settlement.oblast_id %></td>
        <td><%= settlement.district_id %></td>
        <td><%= settlement.aiyl_aimak_id %></td>
        <td><%= settlement.name %></td>
        <td><%= settlement.soate %></td>
        <td><%= link_to 'Show', settlement %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/settlements/new.html.erb
<h1>New Settlement</h1>

<%= render 'form', settlement: @settlement %>

<%= link_to 'Back', settlements_path %>

app/views/settlements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oblast:</strong>
  <%= @settlement.oblast_id %>
</p>

<p>
  <strong>District:</strong>
  <%= @settlement.district_id %>
</p>

<p>
  <strong>Aiyl aimak:</strong>
  <%= @settlement.aiyl_aimak_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @settlement.name %>
</p>

<p>
  <strong>Soate:</strong>
  <%= @settlement.soate %>
</p>

<%= link_to 'Back', settlements_path %>