config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  namespace :admin do
      resources :aiyl_aimaks
      resources :settlements
      resources :oblasts
      resources :layers
      resources :infra_projects
      resources :districts
      resources :partners
      resources :owners
      root to: "aiyl_aimaks#index"
    end
  resources :settlements, only: [:index, :show]
  resources :aiyl_aimaks, only: [:index, :show]
  resources :districts, only: [:index, :show]
  resources :oblasts, only: [:index, :show]
  resources :infra_projects, only: [:index, :show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aiyl_aimak.rb
class AiylAimak < ApplicationRecord
  belongs_to :oblast
  belongs_to :district

  has_many :settlements, dependent: :destroy
  has_many :infra_projects, dependent: :destroy
end

app/controllers/admin/aiyl_aimaks_controller.rb
module Admin
  class AiylAimaksController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/aiyl_aimaks_controller.rb
class AiylAimaksController < ApplicationController
  before_action :set_aiyl_aimak, only: [:show, :edit, :update, :destroy]

  # GET /aiyl_aimaks
  # GET /aiyl_aimaks.json
  def index
    @aiyl_aimaks = AiylAimak.all
  end

  # GET /aiyl_aimaks/1
  # GET /aiyl_aimaks/1.json
  def show
  end

  # GET /aiyl_aimaks/new
  def new
    @aiyl_aimak = AiylAimak.new
  end

  # GET /aiyl_aimaks/1/edit
  def edit
  end

  # POST /aiyl_aimaks
  # POST /aiyl_aimaks.json
  def create
    @aiyl_aimak = AiylAimak.new(aiyl_aimak_params)

    respond_to do |format|
      if @aiyl_aimak.save
        format.html { redirect_to @aiyl_aimak, notice: 'Aiyl aimak was successfully created.' }
        format.json { render :show, status: :created, location: @aiyl_aimak }
      else
        format.html { render :new }
        format.json { render json: @aiyl_aimak.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aiyl_aimaks/1
  # PATCH/PUT /aiyl_aimaks/1.json
  def update
    respond_to do |format|
      if @aiyl_aimak.update(aiyl_aimak_params)
        format.html { redirect_to @aiyl_aimak, notice: 'Aiyl aimak was successfully updated.' }
        format.json { render :show, status: :ok, location: @aiyl_aimak }
      else
        format.html { render :edit }
        format.json { render json: @aiyl_aimak.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aiyl_aimaks/1
  # DELETE /aiyl_aimaks/1.json
  def destroy
    @aiyl_aimak.destroy
    respond_to do |format|
      format.html { redirect_to aiyl_aimaks_url, notice: 'Aiyl aimak was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aiyl_aimak
      @aiyl_aimak = AiylAimak.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aiyl_aimak_params
      params.require(:aiyl_aimak).permit(:oblast_id, :district_id, :name, :soate)
    end
end

app/helpers/aiyl_aimaks_helper.rb
module AiylAimaksHelper
end

app/views/aiyl_aimaks/_form.html.erb
<%= form_with(model: aiyl_aimak, local: true) do |form| %>
  <% if aiyl_aimak.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aiyl_aimak.errors.count, "error") %> prohibited this aiyl_aimak from being saved:</h2>

      <ul>
        <% aiyl_aimak.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :oblast_id %>
    <%= form.text_field :oblast_id %>
  </div>

  <div class="field">
    <%= form.label :district_id %>
    <%= form.text_field :district_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :soate %>
    <%= form.text_field :soate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aiyl_aimaks/edit.html.erb
<h1>Editing Aiyl Aimak</h1>

<%= render 'form', aiyl_aimak: @aiyl_aimak %>

<%= link_to 'Show', @aiyl_aimak %> |
<%= link_to 'Back', aiyl_aimaks_path %>

app/views/aiyl_aimaks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Aiyl Aimaks</h1>

<table>
  <thead>
    <tr>
      <th>Oblast</th>
      <th>District</th>
      <th>Name</th>
      <th>Soate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @aiyl_aimaks.each do |aiyl_aimak| %>
      <tr>
        <td><%= aiyl_aimak.oblast_id %></td>
        <td><%= aiyl_aimak.district_id %></td>
        <td><%= aiyl_aimak.name %></td>
        <td><%= aiyl_aimak.soate %></td>
        <td><%= link_to 'Show', aiyl_aimak %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/aiyl_aimaks/new.html.erb
<h1>New Aiyl Aimak</h1>

<%= render 'form', aiyl_aimak: @aiyl_aimak %>

<%= link_to 'Back', aiyl_aimaks_path %>

app/views/aiyl_aimaks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Oblast:</strong>
  <%= @aiyl_aimak.oblast_id %>
</p>

<p>
  <strong>District:</strong>
  <%= @aiyl_aimak.district_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @aiyl_aimak.name %>
</p>

<p>
  <strong>Soate:</strong>
  <%= @aiyl_aimak.soate %>
</p>

<%= link_to 'Back', aiyl_aimaks_path %>