config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  namespace :admin do
      resources :aiyl_aimaks
      resources :settlements
      resources :oblasts
      resources :layers
      resources :infra_projects
      resources :districts
      resources :partners
      resources :owners
      root to: "aiyl_aimaks#index"
    end
  resources :settlements, only: [:index, :show]
  resources :aiyl_aimaks, only: [:index, :show]
  resources :districts, only: [:index, :show]
  resources :oblasts, only: [:index, :show]
  resources :infra_projects, only: [:index, :show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/layer.rb
class Layer < ApplicationRecord
  belongs_to :infra_project
end

app/controllers/admin/layers_controller.rb
module Admin
  class LayersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   foo = Foo.find(params[:id])
    #   foo.update(params[:foo])
    #   send_foo_updated_email
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #  if current_user.super_admin?
    #    resource_class
    #  else
    #    resource_class.with_less_stuff
    #  end
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  before_action :set_layer, only: [:show, :edit, :update, :destroy]

  # GET /layers
  # GET /layers.json
  def index
    @layers = Layer.all
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
  end

  # GET /layers/new
  def new
    @layer = Layer.new
  end

  # GET /layers/1/edit
  def edit
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(layer_params)

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Layer was successfully created.' }
        format.json { render :show, status: :created, location: @layer }
      else
        format.html { render :new }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layers/1
  # PATCH/PUT /layers/1.json
  def update
    respond_to do |format|
      if @layer.update(layer_params)
        format.html { redirect_to @layer, notice: 'Layer was successfully updated.' }
        format.json { render :show, status: :ok, location: @layer }
      else
        format.html { render :edit }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer.destroy
    respond_to do |format|
      format.html { redirect_to layers_url, notice: 'Layer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @layer = Layer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layer_params
      params.require(:layer).permit(:title, :layer_type, :json, :infra_project_id)
    end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.erb
<%= form_with(model: layer, local: true) do |form| %>
  <% if layer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(layer.errors.count, "error") %> prohibited this layer from being saved:</h2>

      <ul>
        <% layer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :layer_type %>
    <%= form.text_field :layer_type %>
  </div>

  <div class="field">
    <%= form.label :json %>
    <%= form.text_area :json %>
  </div>

  <div class="field">
    <%= form.label :infra_project_id %>
    <%= form.text_field :infra_project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<h1>Editing Layer</h1>

<%= render 'form', layer: @layer %>

<%= link_to 'Show', @layer %> |
<%= link_to 'Back', layers_path %>

app/views/layers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Layers</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Json</th>
      <th>Infra project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @layers.each do |layer| %>
      <tr>
        <td><%= layer.title %></td>
        <td><%= layer.layer_type %></td>
        <td><%= layer.json %></td>
        <td><%= layer.infra_project_id %></td>
        <td><%= link_to 'Show', layer %></td>
        <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
        <td><%= link_to 'Destroy', layer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Layer', new_layer_path %>

app/views/layers/new.html.erb
<h1>New Layer</h1>

<%= render 'form', layer: @layer %>

<%= link_to 'Back', layers_path %>

app/views/layers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @layer.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @layer.layer_type %>
</p>

<p>
  <strong>Json:</strong>
  <%= @layer.json %>
</p>

<p>
  <strong>Infra project:</strong>
  <%= @layer.infra_project_id %>
</p>

<%= link_to 'Edit', edit_layer_path(@layer) %> |
<%= link_to 'Back', layers_path %>