config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new" # custom path to login/sign_in
    get "/sign_up" => "devise/registrations#new", as: "new_user_registration" # custom path to sign_up/registration
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end
  namespace :admin do
      resources :aiyl_aimaks
      resources :settlements
      resources :oblasts
      resources :layers
      resources :infra_projects
      resources :districts
      resources :partners
      resources :owners
      root to: "aiyl_aimaks#index"
    end
  resources :settlements, only: [:index, :show]
  resources :aiyl_aimaks, only: [:index, :show]
  resources :districts, only: [:index, :show]
  resources :oblasts, only: [:index, :show]
  resources :infra_projects, only: [:index, :show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/aiyl_aimak.rb
class AiylAimak < ApplicationRecord
  belongs_to :oblast
  belongs_to :district

  has_many :settlements, dependent: :destroy
  has_many :infra_projects, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
  belongs_to :oblast

  has_many :aiyl_aimaks, dependent: :destroy
  has_many :settlements, dependent: :destroy
  has_many :infra_projects, dependent: :destroy
end

app/models/infra_project.rb
class InfraProject < ApplicationRecord
  belongs_to :oblast
  belongs_to :district
  belongs_to :aiyl_aimak, optional: true
  belongs_to :district
  belongs_to :settlement, optional: true

  has_many :layers, dependent: :destroy

  has_and_belongs_to_many :owners
  has_and_belongs_to_many :partners

  validates :start_date, presence: true
  validates :status, presence: true

  paginates_per 10
end

app/models/layer.rb
class Layer < ApplicationRecord
  belongs_to :infra_project
end

app/models/oblast.rb
class Oblast < ApplicationRecord
  has_many :districts, dependent: :destroy
  has_many :aiyl_aimaks, dependent: :destroy
  has_many :settlements, dependent: :destroy
  has_many :infra_projects, dependent: :destroy
end

app/models/owner.rb
class Owner < ApplicationRecord
  has_and_belongs_to_many :infra_projects
end

app/models/partner.rb
class Partner < ApplicationRecord
  has_and_belongs_to_many :infra_projects
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  belongs_to :oblast
  belongs_to :district
  belongs_to :aiyl_aimak

  has_many :infra_projects, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  before_action :set_layer, only: [:show, :edit, :update, :destroy]

  # GET /layers
  # GET /layers.json
  def index
    @layers = Layer.all
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
  end

  # GET /layers/new
  def new
    @layer = Layer.new
  end

  # GET /layers/1/edit
  def edit
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(layer_params)

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Layer was successfully created.' }
        format.json { render :show, status: :created, location: @layer }
      else
        format.html { render :new }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layers/1
  # PATCH/PUT /layers/1.json
  def update
    respond_to do |format|
      if @layer.update(layer_params)
        format.html { redirect_to @layer, notice: 'Layer was successfully updated.' }
        format.json { render :show, status: :ok, location: @layer }
      else
        format.html { render :edit }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer.destroy
    respond_to do |format|
      format.html { redirect_to layers_url, notice: 'Layer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @layer = Layer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layer_params
      params.require(:layer).permit(:title, :layer_type, :json, :infra_project_id)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @layers = Layer.all
    @infras = InfraProject.all
  end
end

app/helpers/aiyl_aimaks_helper.rb
module AiylAimaksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/helpers/infra_projects_helper.rb
module InfraProjectsHelper
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/helpers/oblasts_helper.rb
module OblastsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/settlements_helper.rb
module SettlementsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aga Khan Foundation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
          integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
          crossorigin=""/>

    <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
            integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
            crossorigin="">
    </script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.css" integrity="sha256-+bdWuWOXMFkX0v9Cvr3OWClPiYefDQz9GGZP/7xZxdc=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/MarkerCluster.Default.css" integrity="sha256-LWhzWaQGZRsWFrrJxg+6Zn8TT84k0/trtiHBc6qcGpY=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.4.1/leaflet.markercluster.js" integrity="sha256-WL6HHfYfbFEkZOFdsJQeY7lJG/E5airjvqbznghUzRw=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha256-R4pqcOYV8lt7snxMQO/HSbVCFRPMdrhAFMH+vr9giYI=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.css" integrity="sha256-IvM9nJf/b5l2RoebiFno92E5ONttVyaEEsdemDC6iQA=" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/gh/emn178/chartjs-plugin-labels/src/chartjs-plugin-labels.js">

    </script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <nav class="navbar navbar-expand-sm navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to root_path, class:"navbar-brand"  do %>
        <%= image_tag "akf-logo.png", style:"height: 50px"%>
      <% end %>
      <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
              aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class:'nav-link' %>
          </li>
          <!--
          <li class="nav-item">
            <%= link_to 'Oblasts', oblasts_path, class:'nav-link' %>
          </li>
          <li class="nav-item ">
            <%= link_to 'Districts', districts_path, class: 'nav-link' %>
          </li>
          -->
          <li class="nav-item">
            <%= link_to 'Infra Projects', infra_projects_path, class:'nav-link' %>
          </li>
        </ul>
      </div>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.email %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Admin panel', admin_root_path, class:'dropdown-item' %>
              <%= link_to 'Account', edit_user_registration_path(current_user), class:'dropdown-item' %>
              <div class="dropdown-divider"></div>
              <%= link_to 'Log out', destroy_user_session_path, method: :delete , class:'dropdown-item'%>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Log in', sign_in_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>

    </div>
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>
  </body>
</html>